name: CI

on:
  push:
  pull_request:

jobs:

  # It is much faster to validate k8s manifests before running integration tests
  
  kubernetes-manifest-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      # Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        
      # kubectl dry run
      - name: Validate manifests with kubeconform
        run: | 

          # Install kubeconform
          wget -O kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/
          chmod +x /usr/local/bin/kubeconform

          # Validate manifests
          kubeconform -strict -summary k8s/**/*.yaml
          kubeconform -strict -summary k8s/*.yaml

          # Validation message
          echo "Kubernetes manifests validated successfully"


  frontend-backend-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Start containers
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Pull lightweight model
        run: docker compose exec -T ollama ollama pull smollm2:135m

      - name: Backend test 
        run: |
          sleep 10 && \
          curl -X POST http://localhost:8000/api/chat \
            -H "Content-Type: application/json" \
            -d '{"model":"smollm2:135m","messages":[{"role":"user","content":"say backend ok"}]}' \
            | grep '"message"'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install Playwright
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: Run frontend test
        working-directory: frontend
          
        run: npx playwright test tests/chat.spec.js

      - name: Logs if failed
        if: failure()
        run: docker compose logs 